/*
3474. Lexicographically Smallest Generated String

You are given two strings, str1 and str2, of lengths n and m, respectively.
A string word of length n + m - 1 is defined to be generated by str1 and str2 if it satisfies the following conditions for each index 0 <= i <= n - 1:
If str1[i] == 'T', the substring of word with size m starting at index i is equal to str2, i.e., word[i..(i + m - 1)] == str2.
If str1[i] == 'F', the substring of word with size m starting at index i is not equal to str2, i.e., word[i..(i + m - 1)] != str2.
Return the lexicographically smallest possible string that can be generated by str1 and str2. If no string can be generated, return an empty string "".

Example 1:
Input: str1 = "TFTF", str2 = "ab"
Output: "ababa"
Explanation:
The table below represents the string "ababa"
Index	T/F	Substring of length m
0	'T'	"ab"
1	'F'	"ba"
2	'T'	"ab"
3	'F'	"ba"
The strings "ababa" and "ababb" can be generated by str1 and str2.
Return "ababa" since it is the lexicographically smaller string.

Example 2:
Input: str1 = "TFTF", str2 = "abc"
Output: ""
Explanation:
No string that satisfies the conditions can be generated.

Example 3:
Input: str1 = "F", str2 = "d"
Output: "a"

Constraints:
1 <= n == str1.length <= 10¨4
1 <= m == str2.length <= 500
str1 consists only of 'T' or 'F'.
str2 consists only of lowercase English characters.

</> Typescript code:
*/

function generateString(str1: string, str2: string): string {
  const n = str1.length;
  const m = str2.length;
  const wordLen = n + m - 1;
  // Use an array to build the string; null represents an unassigned/flexible character.
  const res: (string | null)[] = new Array(wordLen).fill(null);
  // Track indices forced by a 'T' condition so we don't change them later.
  const fixed = new Uint8Array(wordLen);

  // First pass: Fill in all characters required by 'T' conditions.
  for (let i = 0; i < n; i++) {
    if (str1[i] === "T") {
      for (let j = 0; j < m; j++) {
        // If a 'T' overlaps with another 'T' but requires a different character, it's impossible.
        if (res[i + j] !== null && res[i + j] !== str2[j]) return "";
        res[i + j] = str2[j];
        fixed[i + j] = 1; // Mark as unchangeable.
      }
    }
  }

  // Fill all unassigned spots with 'a' to keep the string lexicographically smallest.
  for (let i = 0; i < wordLen; i++) {
    if (res[i] === null) res[i] = "a";
  }

  // Second pass: Validate 'F' conditions and break accidental matches.
  for (let i = 0; i < n; i++) {
    if (str1[i] === "F") {
      let match = true;
      for (let j = 0; j < m; j++) {
        if (res[i + j] !== str2[j]) {
          match = false;
          break;
        }
      }

      // If an 'F' index actually matches str2, we must modify the word.
      if (match) {
        let changed = false;
        // Try to change the rightmost character possible to minimize lexicographical impact.
        for (let j = m - 1; j >= 0; j--) {
          if (!fixed[i + j]) {
            // Check characters from 'a' to 'z' to find the smallest one that isn't str2[j].
            for (let charCode = 97; charCode <= 122; charCode++) {
              const char = String.fromCharCode(charCode);
              if (char !== str2[j]) {
                res[i + j] = char;
                changed = true;
                break;
              }
            }
            if (changed) break;
          }
        }
        // If every character in the matching substring was fixed by 'T's, we can't break the match.
        if (!changed) return "";
      }
    }
  }

  return res.join("");
}
